name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/business-rule-engine

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install hatch
      run: pip install hatch
    - name: Build
      run: hatch build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
